// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPzvjtXUhK21PNzHGdwtUk2DvQgMGtPfs',
    appId: '1:951530390148:web:05340ef570b71e7cc038d1',
    messagingSenderId: '951530390148',
    projectId: 'plasma-fecd2',
    authDomain: 'plasma-fecd2.firebaseapp.com',
    storageBucket: 'plasma-fecd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjzfjXd_G7oKcFfHTH0HLEDf_BA2PBWOo',
    appId: '1:951530390148:android:9af6abd8e2638f00c038d1',
    messagingSenderId: '951530390148',
    projectId: 'plasma-fecd2',
    storageBucket: 'plasma-fecd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjMGXVtRVhUkp-ROC4R1MRwRxzYXEsoU',
    appId: '1:951530390148:ios:1c36023c3dd8f63ac038d1',
    messagingSenderId: '951530390148',
    projectId: 'plasma-fecd2',
    storageBucket: 'plasma-fecd2.appspot.com',
    iosClientId: '951530390148-6m9fo15oe2qimt1ks6t9k2bs5rvs69kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.plasma',
  );
}
